export const LOAD_PRODUCTS = "LOAD_PRODUCTS";

export const SET_USER = "SET_USER";

export const LOAD_CART = "LOAD_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const UPDATE_CART_SUM = "UPDATE_CART_SUM";
export const CART_QUANTITY_UP = "CART_QUANTITY_UP";
export const CART_QUANTITY_DOWN = "CART_QUANTITY_DOWN";

export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const LOAD_WISHLIST = "LOAD_WISHLIST";
export const LOAD_WISHLIST_PRODUCTS = "LOAD_WISHLIST_PRODUCTS";

export const LOAD_ACCOUNT_INFO = "LOAD_ACCOUNT_INFO";
export const CREATE_ACCOUNT_INFO = "CREATE_ACCOUNT_INFO";
export const DELETE_ACCOUNT_INFO = "DELETE_ACCOUNT_INFO";

export const LOAD_SHIPMENT_INFO = "LOAD_SHIPMENT_INFO";
export const CREATE_SHIPMENT_INFO = "CREATE_SHIPMENT_INFO";
export const DELETE_SHIPMENT_INFO = "DELETE_SHIPMENT_INFO";

export const CREATE_ORDER = "CREATE_ORDER";
export const CREATE_PAYMENT = "CREATE_PAYMENT";
